# Reusable workflow for testing something using
name: Bun CI

on:
  workflow_call:
    inputs:
      jsr_dependencies:
        description: 'Space-separated list of dependencies to install'
        required: true
        type: string 
      npm_dependencies:
        description: 'Space-separated list of dependencies to install from NPM'
        type: string 

jobs:
  bun_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: antongolub/action-setup-bun@v1.13.1 
        with:
          bun-version: v1.x # Uses latest bun 1
      - run: bun x jsr add ${{ inputs.jsr_dependencies }}  # Installs dependencies
      - name: Install NPM Dependencies
        if: ${{ inputs.npm_dependencies }}
        run: npm install ${{ inputs.npm_dependencies }} 
      - run: bun test # Runs the tests