# Reusable workflow for testing something using Deno
# - Checks formatting, linting and 
name: Deno CI

on:
  workflow_call:
    inputs:
      entrypoint:
        description: 'Entrypoint javascript file'
        required: true
        type: string 
      lint_docs:
        description: 'Lint docs'
        default: true
        type: boolean 
      run_tests:
        description: 'Run tests'
        default: true
        type: boolean 
      allow_outdated:
        description: 'Allow outdated deps'
        default: true
        type: boolean 
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Check types
        run: deno check ${{ inputs.entrypoint }} 

      - name: Lint the docs
        if: ${{ inputs.lint_docs }}
        run: deno doc --lint ${{ inputs.entrypoint }} 

      - name: Run tests
        if: ${{ inputs.run_tests }}
        run: deno test -A

      - name: Check Dependencies
        continue-on-error: ${{ inputs.allow_outdated }}
        run: deno run -A jsr:@check/deps || echo "::warning title=Dependency Check::Some of the dependencies are out of date, please check."

