# Reusable workflow for testing something using Node.js
# - Will use both the oldest LTS and most recent version
# - Will expect a main branch

name: Node.js CI

on:
  workflow_call:
    inputs:
      jsr_dependencies:
        description: 'Space-separated list of dependencies to install'
        required: true
        type: string 
      npm_dependencies:
        description: 'Space-separated list of dependencies to install from NPM'
        type: string 
      test_target:
        description: 'Target path for tests, example: *.test.ts'
        type: string 
        default: "*.test.ts"
jobs:
  node_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
      - run: npx jsr add ${{ inputs.jsr_dependencies }}
      - name: Install NPM Dependencies
        if: ${{ inputs.npm_dependencies }}
        run: npm install ${{ inputs.npm_dependencies }} 
      - run: "echo '{ \"type\": \"module\" }' > package.json" # Needed for tsx to work
      - run: npx --yes tsx --test ${{ inputs.test_target }}
